### PR TITLE
Add loongarch support and a new command-line option

### PR DESCRIPTION
**Pull request by jinboson**
Hi, MaartenBaert:

Thanks for your outstanding work!  We add loongarch support for SSR and make a minor modification on loongarch. We hope to merge this into master branch.

Thanks,
Jin Bo.

### CODE REVIEW

**Comment by MaartenBaert** [comment]
Thanks for the contribution, I have one question though: what is the purpose of this:
```
#if defined(__loongarch__)
	GoPageRecord();
#endif
```
This does not seem to have anything to do with the CPU architecture.

**Comment by jinboson** [comment]
> Hi, Maarten:
Thanks for your reply!
In most cases, the defaut configurations work very well. For end-users they maybe even don't konw the true meanings of these paramters on InputPage and OutPage. So, in order to make it more easy to use SSR, skip directly to RecordPage as SSR starts. 
Thanks,
Jin Bo.

**Comment by jinboson** [comment]
> Thanks for the contribution, I have one question though: what is the purpose of this:
> 
> ```
> #if defined(__loongarch__)
> 	GoPageRecord();
> #endif
> ```
> 
> This does not seem to have anything to do with the CPU architecture.

Hi, Maarten:
Thanks for your reply!

You are right. The second patch has nothing to do with the CPU architechure. It's just a minor improvement of simplifing the way of using SSR on the CPU architecture. Do I need to create a new pullrequest for the second patch ?

Thanks,
Jin Bo.

**Comment by jinboson** [comment]
> Thanks for the contribution, I have one question though: what is the purpose of this:
> 
> ```
> #if defined(__loongarch__)
> 	GoPageRecord();
> #endif
> ```
> 
> This does not seem to have anything to do with the CPU architecture.

Thanks for your reply!

You are right. The second patch has nothing to do with the CPU architechure. It's just a minor improvement of simplifying the way of using SSR on the CPU architecture. Because, for most end-users , they maybe don't know the true meanings of the parameters in InputPage and OutputPage, and in most cases, the default configurations work very well, so just skip directly to PageRecord instead of clicking 'continue button' every time as SSR starts.
BTW, do I need to create a new pullrequest for the second patch ?

Thanks,
Jin Bo.

**Comment by MaartenBaert** [comment]
I think it would be better to add a command-line option that defines the starting page (welcome, input, output or record) so it doesn't have to be baked into the software. It certainly doesn't make sense to change the starting page depending on the CPU architecture.

**Comment by jinboson** [comment]
ok, I will try.

**Comment by jinboson** [comment]
Hi, Maarten:

I have updated the second patch according to your advice.

Thanks,
Jin Bo.

**Comment by jinboson** [comment]
Hi, Maarten:

Is it possible to merge the PR into master ?

**Pull request closed without merging**
