### PR TITLE
Fixing compilation issues for latest FFMPEG 

### PR DESCRIPTION
**Pull request by DistantThunder**
Replaced some occurences of 'PixelFormat' with 'AVPixelFormat' since ssr couldn't compile with latest FFMPEG from git.

### CODE REVIEW

**Comment by DistantThunder** [comment]
https://github.com/MaartenBaert/ssr/issues/371

**Comment by MaartenBaert** [comment]
IIRC this will break compilation with libav. That's why AVWrapper exists. I will look into it later.

**Comment by DistantThunder** [comment]
Mmh? What about [this](https://github.com/libav/libav/blob/7bb1c1bfd22de2200743af04ebd0c7c775f56f7e/doc/APIchanges#L552)?

**Comment by MaartenBaert** [comment]
I want to maintain compatibility with Ubuntu 12.04 LTS, which has a really old version of libav.

The right solution is to add an exception to AVWrapper which defines AVPixelFormat to PixelFormat when compiled with an older version of ffmpeg/libav. I'm working on it.

**Comment by DistantThunder** [comment]
> I want to maintain compatibility with Ubuntu 12.04 LTS, which has a really old version of libav.

OK, good luck with that. I tried that for PPSSPP as the same problem arised but was unable to query the version number in the end. May the coding-foo be with you.

**Comment by MaartenBaert** [comment]
Take a look at Global.h. I already have a dozen version checks there to deal with all the API changes that have happened during the last 4 years. One more doesn't hurt :).

**Comment by DistantThunder** [comment]
Thanks, I'll peek at Global.h and try to understand what's going on in the #define (s)!

**Pull request merged**
